### PR TITLE
Get rid of antd

### PR DESCRIPTION
**Pull request by sergous**
Remove antd from deps is ready.
Refactor with styled-components is up to go.

### CODE REVIEW

**Comment by sergous** [comment]
Refactored with styled-components. 
antd styles file have animation and icons, which are used in Modal component, so can't be deleted without regressions.
Please review @optimusway

**Comment by sergous** [comment]
I have Idea how to get rid from this deps:
    "rc-dialog": "^7.0.4",
    "rc-dropdown": "^2.1.0",
and refactor them with styled-components, continuing working on this task.

**Comment by sergous** [comment]
rc-dropdown removed, modal dialog to go.

**Comment by sergous** [comment]
rc-dialog removed, please review @optimusway

**Comment by sergous** [comment]
Almost done, going to refactor ModalDialog with styled.

**Comment by optimusway** [comment]
hi there!

plz check out the corresponding task to see some issues I've found

**Comment by sergous** [comment]
Rebased, fount fixes are committed.

**Comment by sergous** [comment]
Updated, please review 
@optimusway

**Comment by sergous** [comment]
Dropdown refactored.
Merge dev to include latest changes.
Please review @optimusway

**Comment by sergous** [comment]
As agreed, I added theme interface to styled components.

**Comment by sergous** [comment]
Files renamed to camelCase, please review @optimusway

**Pull request merged**
